### ISSUE TITLE
BIG ERROR

### ISSUE THREAD

**Issue by kingcharaf99** [EmoteBot/EmoteManager#28]
This is my error down below please help

[SolverProblemError]
Because aioec (0.6.1) depends on aiohttp (>=3.6.0,<3.7.0)
 and no versions of aioec match >0.6.1,<0.7.0, aioec (>=0.6.1,<0.7.0) requires aiohttp (>=3.6.0,<3.7.0).
So, because repl-python3-beta-emoji depends on both aioec (^0.6.1) and aiohttp (^3.7.4), version solving failed.
exit status 1

**Comment by ioistired** [comment]
Try now

**Comment by kingcharaf99** [comment]
> Try now

It didn't work. Please help me

 python bot.py
INFO:discord.client:Cleaning up tasks.
INFO:discord.client:Cleaning up after 1 tasks.
INFO:discord.client:All tasks finished cancelling.
INFO:discord.client:Closing the event loop.
Traceback (most recent call last):
  File "bot.py", line 102, in <module>
    main()
  File "bot.py", line 80, in main
    Bot(
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 723, in run
    return future.result()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/bot_bin/bot.py", line 179, in start
    self.load_extensions()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/bot_bin/bot.py", line 195, in load_extensions
    self.load_extension(extension)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 676, in load_extension
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension 'jishaku' could not be loaded.
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb15a44a760>
exit status 1


**Comment by ioistired** [comment]
you need to install jishaku. use the requirements.txt file `pip install -Ur requirements.txt`

**Comment by kingcharaf99** [comment]
> you need to install jishaku. use the requirements.txt file `pip install -Ur requirements.txt`

Thank you so much! It worked.
